# Generated by Django 4.2.3 on 2023-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='apply_link',
            field=models.CharField(default='#', max_length=400),
        ),
    ]
