# Generated by Django 4.2.3 on 2023-12-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_details_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='company_logo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
